symbol_engine.settings:
  type: config_object
  label: 'Symbol Engine settings'
  mapping:
    engine_base_url:
      type: string
      label: 'Engine base URL'
    engine_timeout:
      type: integer
      label: 'Engine timeout seconds'

